import type { Metadata } from "next";
import { Geist, Geist_Mono, Great_Vibes, Tilt_Prism, Architects_Daughter, Rubik_Doodle_Shadow } from "next/font/google";
import "./globals.css";
import { DottedLayout } from "./dotted-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: ["400"],
});

const tiltPrism = Tilt_Prism({
  variable: "--font-tilt-prism",
  subsets: ["latin"],
  weight: ["400"],
});

const architectsDaughter = Architects_Daughter({
  variable: "--font-architects-daughter",
  subsets: ["latin"],
  weight: ["400"],
});

const rubikDoodleShadow = Rubik_Doodle_Shadow({
  variable: "--font-rubik-doodle-shadow",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${greatVibes.variable} ${tiltPrism.variable} ${architectsDaughter.variable} ${rubikDoodleShadow.variable} antialiased`}
      >
        <DottedLayout>{children}</DottedLayout>
      </body>
    </html>
  );
}
